language: go
sudo: false
go:
  - 1.10
git:
  depth: 1

install:
  - make install

go_import_path: github.com/nightlegend/grpc-server-go

script:
  - make vet
  - make fmt-check
  - make test  

after_success:
  - bash <(curl -s https://codecov.io/bash)